// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotelReserv.Data;

namespace hotelReserv.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("hotelReserv.Data.Entities.HotelEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about");

                    b.Property<string>("facebook");

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<string>("nationality");

                    b.Property<string>("oficialPage");

                    b.Property<string>("ubication");

                    b.Property<string>("url_logo_image");

                    b.HasKey("id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("hotelReserv.Data.Entities.ReservEntity", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("departure");

                    b.Property<DateTime>("entry");

                    b.Property<int?>("hotelId");

                    b.HasKey("id");

                    b.HasIndex("hotelId");

                    b.ToTable("Reservs");
                });

            modelBuilder.Entity("hotelReserv.Data.Entities.ReservEntity", b =>
                {
                    b.HasOne("hotelReserv.Data.Entities.HotelEntity", "hotelIdEntity")
                        .WithMany("reservs")
                        .HasForeignKey("hotelId");
                });
#pragma warning restore 612, 618
        }
    }
}
